### ISSUE TITLE
Learning installer/configuration system for Archivematica (Russell)

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Digital-Preservation#19]
I need to set up an environment at my home office for test/development, similar to what Hugo did in #14 for other CRKN staff.

**Comment by RussellMcOrmond** [comment]
On my own time I need to clean up my server environment.  While I can do this on my laptop, I would prefer to get this all set up on a local server.

**Comment by hstgelais-crkn-rcdr** [comment]
Let me know if you need help setting it up as a vm on your server environment. I think the documentation is clear enough but just in case.

**Comment by RussellMcOrmond** [comment]
I'm reading all the comments you are making on the other tickets.  If I run into troubles, we'll want to throw whatever we learn into the Wiki so we'll know for next time.  I get the impression with Archivematica that we'll be installing it many times in many different environments, so will want good notes.

**Comment by RussellMcOrmond** [comment]
* Following Docs that Hugo wrote in order to suggest any enhancements to docs:
https://github.com/crkn-rcdr/Systems-Administration/blob/main/wiki/documentation/archivematica.md


* Already had bridge set up, so told Vagrant to connect to that bridge when it asked.

```
==> am-local: Available bridged network interfaces:
1) br0
2) virbr0
3) enp3s0
4) docker0
==> am-local: When choosing an interface, it is usually the one that is
==> am-local: being used to connect to the internet.
    am-local: Which interface should the network bridge to? 1
```


```
root@westbengal:~# cat /etc/netplan/50-ethernet.yaml 
network:
    ethernets:
        enp3s0:
          dhcp4: false
    bridges:
        br0:
            interfaces: [enp3s0]
            addresses:
            - 192.168.142.133/24
            - 192.168.142.105/24
            dhcp4: false
            nameservers:
              search: [int.flora.ca,flora.ca]
              addresses: [192.168.142.252]
            gateway4: 192.168.142.252
    version: 2
root@westbengal:~# 

```


* Additional python dependency "jmespath" needed for vagrant.
https://github.com/artefactual-labs/ansible-archivematica-src/blob/stable/1.13.x/README.md#dependencies


* Issues with networking -- seems I have to let everything install with the default networking, and then halt the VM, change to what I want, and then do a `vagrant provision`

```
archivematica@westbengal:~/archivematica-1.13.0/deploy-pub/playbooks/archivematica-bionic$ git diff
diff --git a/playbooks/archivematica-bionic/Vagrantfile b/playbooks/archivematica-bionic/Vagrantfile
index f8f0ff0..6615033 100644
--- a/playbooks/archivematica-bionic/Vagrantfile
+++ b/playbooks/archivematica-bionic/Vagrantfile
@@ -10,7 +10,8 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
   {
     "am-local" => {
-      "ip" => "192.168.168.198",
+      #"ip" => "192.168.168.198",
+      "ip" => "192.168.142.134",
       "memory" => "4096",
       "cpus" => "2",
     },
@@ -18,7 +19,8 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
     # Define guest
     config.vm.define short_name do |host|
-      host.vm.network "private_network", ip: properties.fetch("ip")
+      host.vm.network "public_network", ip: properties.fetch("ip")
+      #host.vm.network "private_network", ip: properties.fetch("ip")
       host.vm.hostname = "#{short_name}.myapp.dev"
     end
 
archivematica@westbengal:~/archivematica-1.13.0/deploy-pub/playbooks/archivematica-bionic$ 

```

Then I needed to go into Archivematica and tell it where the Storage Server was now (it had the default IP addresses in it).

* Created a new transfer source that pointed to `/home/vagrant/archivematica-sampledata/SampleTransfers` , as that is where the samples are.

* Did a transfer of "BagTransferr, creating and storing an AIP and a DIP.

* Still need to figure out networking, as the default route is to the private network and not via the static IP address.
